### ISSUE TITLE
Figure out how to spin a motor at a fixed speed using closed loop control

### ISSUE THREAD

**Issue by mcolinj** [FRC1076/2020-Competition#37]
https://www.ctr-electronics.com/downloads/pdf/Legacy%20Talon%20SRX%20Software%20Reference%20Manual.pdf

Note that you can configure the TalonSRX to run at a certain speed using its built-in PID control.   Take the example code from this documentation and see if you can spin the motor at fixed speeds.

See, especially, the Java code in section 12.4 for how to configure the motor controller.

**Comment by EmilyRobotics** [comment]
Closed as we are no longer using ctre
