### ISSUE TITLE
Get the color sensor to work

### ISSUE THREAD

**Issue by VeeBallbach** [FRC1076/2020-Competition#4]
As of right now, robotpy doesn't have any code to use the color sensor, so we need to do it ourselves. The sensor is a Rev Color Sensor 3, and we need to use robotpy's [I2C class](https://robotpy.readthedocs.io/projects/wpilib/en/latest/wpilib/I2C.html) to connect with it. The hex values to read can be found in [the file here.](https://github.com/FRC1076/2020-Competition/files/4056483/APDS-9151-DS104.pdf)

**Comment by VeeBallbach** [comment]
This is a very late addition, but robotpy 2020 has support for the color sensor, so we need to test that sometime soon

**Comment by VeeBallbach** [comment]
Check https://robotpy.readthedocs.io/en/latest/install/revcolor.html for information about using the color sensor

**Comment by EmilyRobotics** [comment]
Basically donr
