### ISSUE TITLE
Can't install robotpy-rev

### ISSUE THREAD

**Issue by numerator** [FRC1076/2020-Competition#59]
I am trying to get the simulator running but the master branch code requires the `rev` package. When I try to  run `pip install robotpy-rev` I get the following error, which causes the install to fail:

`Downloading http://www.revrobotics.com/content/sw/max/sdk/maven/com/revrobotics/frc/SparkMax-driver/1.5.2/SparkMax-driver-1.5.2-windowsx86.zip
  error: HTTP Error 404: Not Found`

It seems that the required file is no longer at that location. Has anyone else seen this and found a fix or workaround?

**Comment by EmilyRobotics** [comment]
Try running `py -3 -m pip install robotpy-rev robotpy-rev-color `

**Comment by EmilyRobotics** [comment]
If that does not work, can you post the output of `pip --version`

**Comment by numerator** [comment]
$ py -3 -m pip install --user robotpy-rev robotpy-rev-color
Collecting robotpy-rev
  Using cached robotpy-rev-2020.1.1.tar.gz (18 kB)
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for robotpy-rev from htt
ps://files.pythonhosted.org/packages/12/e1/eddd776ffa8620defcf97d9cbeaba7b8ca7e1
992f9285825e2b07db2642c/robotpy-rev-2020.1.1.tar.gz#sha256=6ee57f0e4c0fe57765660
2641dd7390ac9554bdbe56c84c2704905b8799a5189.
  WARNING: The project does not specify a build backend, and pip cannot fall bac
k to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting robotpy-rev-color
  Downloading robotpy_rev_color-2020.1.2.0-cp38-cp38-win32.whl (73 kB)
     |████████████████████████████████| 73 kB 1.3 MB/s
Requirement already satisfied: wpilib>=2020.2.2.0 in c:\users\mwnewman\appdata\r
oaming\python\python38\site-packages (from robotpy-rev) (2020.3.2.4)
Requirement already satisfied: robotpy-wpiutil<2021.0.0,>=2020.2.2.0 in c:\users
\mwnewman\appdata\roaming\python\python38\site-packages (from robotpy-rev) (2020
.3.2.0)
Requirement already satisfied: robotpy-hal<2021.0.0,>=2020.3.2.0 in c:\users\mwn
ewman\appdata\roaming\python\python38\site-packages (from wpilib>=2020.2.2.0->ro
botpy-rev) (2020.3.2.5)
Requirement already satisfied: pyntcore<2021.0.0,>=2020.3.2.0 in c:\users\mwnewm
an\appdata\roaming\python\python38\site-packages (from wpilib>=2020.2.2.0->robot
py-rev) (2020.3.2.1)
Requirement already satisfied: pynetworktables<2021.0.0,>=2020.0.3 in c:\users\m
wnewman\appdata\roaming\python\python38\site-packages (from pyntcore<2021.0.0,>=
2020.3.2.0->wpilib>=2020.2.2.0->robotpy-rev) (2020.0.3)
Building wheels for collected packages: robotpy-rev
  Building wheel for robotpy-rev (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files (x86)\Python38-32\python.exe' 'C:\Users\mwnewman\A
ppData\Roaming\Python\Python38\site-packages\pip\_vendor\pep517\_in_process.py'
build_wheel 'C:\cygwin64\tmp\tmps4gtax8_'
       cwd: C:\cygwin64\tmp\pip-install-_7pdhwma\robotpy-rev
  Complete output (8 lines):
  running bdist_wheel
  running build
  running build_py
  running build_gen
  running build_dl
  Downloading http://www.revrobotics.com/content/sw/max/sdk/maven/com/revrobotic
s/frc/SparkMax-driver/1.5.2/SparkMax-driver-1.5.2-headers.zip
  101%Downloading http://www.revrobotics.com/content/sw/max/sdk/maven/com/revrob
otics/frc/SparkMax-driver/1.5.2/SparkMax-driver-1.5.2-windowsx86.zip
  error: HTTP Error 404: Not Found
  ----------------------------------------
  ERROR: Failed building wheel for robotpy-rev
Failed to build robotpy-rev
ERROR: Could not build wheels for robotpy-rev which use PEP 517 and cannot be in
stalled directly

**Comment by numerator** [comment]
$ py -3 -m pip --version
pip 20.0.2 from C:\Users\mwnewman\AppData\Roaming\Python\Python38\site-packages\
pip (python 3.8)

**Comment by EmilyRobotics** [comment]
Can you post the output of  `py -3 --version`

**Comment by numerator** [comment]
Now that I look at it perhaps the issue is the "build backend." So if you don't have another suggestion that's what I will look into next.  Maybe this is what you were referring to when you were telling me to install Visual Studio.

**Comment by numerator** [comment]
3.8.1

**Comment by EmilyRobotics** [comment]
Try running it with the command `--no-binary`

**Comment by numerator** [comment]
That worked! Thanks. I'll add that to any documentation I create about setting up a simulator.

**Comment by numerator** [comment]
Still looks like it's necessary to install Visual Studio, as I get this message when I try to run 
`py -3 robot.py sim`:  

Exception: wpiutil.dll could not be loaded. Do you have Visual Studio C++ Redist
ributible 2019 installed?

**Comment by EmilyRobotics** [comment]
You don't need visual studio, just `https://aka.ms/vs/16/release/vc_redist.x64.exe`

**Comment by EmilyRobotics** [comment]
Since that seems to have fixed the problem, I am closing the issue
